### PR TITLE
Add supporters wall of fame, link to it from the home page

### PR DESCRIPTION
**Pull request by Kenadia**
Screenshots:

https://www.dropbox.com/s/maair7bds36xkzh/Screenshot%202015-05-26%2022.10.04.png?dl=0
https://www.dropbox.com/s/e355ymy0x11g6lb/Screenshot%202015-05-26%2022.10.09.png?dl=0

### CODE REVIEW

**Comment by lord** [comment]
Does the two-column look good on mobile? If not, you could stick the new styles in a media query to only show on desktop.

**Comment by Kenadia** [comment]
Thanks for catching that, I think this looks alright now:

iphone
https://www.dropbox.com/s/f0g01zy25du1xdn/Screenshot%202015-05-26%2022.41.53.png?dl=0

cutoff point
https://www.dropbox.com/s/u7einprr2p3kck4/Screenshot%202015-05-26%2022.42.14.png?dl=0
https://www.dropbox.com/s/hd9g2q7lnxruam0/Screenshot%202015-05-26%2022.42.36.png?dl=0

large window
https://www.dropbox.com/s/mcnu55l15g7iof1/Screenshot%202015-05-26%2022.42.44.png?dl=0

**Comment by lord** [comment]
The images are 404s? The code looks good, though!

**Comment by Kenadia** [comment]
images there now! feel free to merge

**Comment by lord** [comment]
:+1: looks great!

**Comment by lord** [comment]
:ship: deployed!

**Pull request merged**
